package main

const (
	PKT_FILE_CREATE          // PAT
	PKT_FILE_UPDATE
	PKT_FILE_DELETE
	PKT_FILE_REQUEST_CHUNK
	PKT_FILE_REQUEST_CHUNK_MAP
	PKT_FILE_CHUNK
	PKT_FILE_CHUNK_MAP
	PKT_CLIENT_INFO
	PKT_SERVER_FILE_TREE
)
